name: Build Python Wheel for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # v4 kullan

      - name: Set up Python
        uses: actions/setup-python@v5  # v5 kullan
        with:
          python-version: '3.13'  # Python 3.13.3'ü belirtiyoruz

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cython  # Cython'ı da kuruyoruz

      - name: Set up Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1  # Visual Studio'yu kuruyoruz
        with:
          vs-version: 'latest'  # En son versiyonunu kullanıyoruz

      - name: Build Wheel
        run: python setup.py bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4  # v4 kullan
        with:
          name: python-wheel
          path: dist/*.whl  # Derlenen wheel dosyasını yükle
